// const { GoogleGenerativeAI } = require("@google/generative-ai"); // Gemini (commented out)
const { CohereClientV2 } = require("cohere-ai");
const path = require("path");
const fs = require("fs");
const axios = require("axios");

// Initialize Cohere
const cohere = new CohereClientV2({
  token: process.env.COHERE_API_KEY,
});

// Gamma API Configuration
const GAMMA_API_BASE = "https://public-api.gamma.app/v1.0";
const GAMMA_API_KEY = process.env.GAMMA_API_KEY;

/**
 * Call Gamma API to create a presentation from text
 * @param {string} inputText - The content to transform into slides
 * @param {object} options - Additional options for generation
 * @returns {object} - Gamma response with deck URL
 */
const createGammaPresentation = async (inputText, options = {}) => {
  if (!GAMMA_API_KEY) {
    throw new Error("GAMMA_API_KEY chưa được cấu hình trong .env");
  }

  try {
    const response = await axios.post(
      `${GAMMA_API_BASE}/generations`,
      {
        inputText: inputText,
        format: "presentation",
        textMode: "preserve", // Keep the text content as generated by Gemini
        numCards: options.numCards || 8,
        exportAs: "pptx", // Export as PowerPoint for direct download
        imageOptions: {
          source: options.stockImages ? "unsplash" : "aiGenerated", // unsplash for free stock, aiGenerated for AI
          style: "colorful, friendly, cartoon style for kids, preschool education"
        },
        textOptions: {
          language: "vi" // Vietnamese
        },
        sharingOptions: {
          workspaceAccess: "view", // Allow workspace members to view
          externalAccess: "view" // Allow external users (teachers) to view without login
        }
      },
      {
        headers: {
          "X-API-KEY": GAMMA_API_KEY,
          "Content-Type": "application/json"
        },
        timeout: 120000 // 2 minutes timeout for generation
      }
    );

    return response.data;
  } catch (error) {
    console.error("Gamma API Error:", error.response?.data || error.message);
    throw new Error(error.response?.data?.message || "Lỗi khi gọi Gamma API");
  }
};

/**
 * Poll Gamma API to get the generated file URLs
 * @param {string} generationId - The generation ID from the create request
 * @returns {object} - The generation result with URLs
 */
const pollGammaGeneration = async (generationId) => {
  const maxAttempts = 30; // Max 2.5 minutes (30 * 5 seconds)
  let attempts = 0;

  while (attempts < maxAttempts) {
    try {
      const response = await axios.get(
        `${GAMMA_API_BASE}/generations/${generationId}`,
        {
          headers: {
            "X-API-KEY": GAMMA_API_KEY,
            "Content-Type": "application/json"
          },
          timeout: 10000
        }
      );

      const data = response.data;
      console.log(`Poll attempt ${attempts + 1}:`, data.status);

      // Check if generation is complete
      if (data.status === "completed" || data.url) {
        return data;
      }

      // Check if generation failed
      if (data.status === "failed" || data.error) {
        throw new Error(data.error || "Gamma generation failed");
      }

      // Wait 5 seconds before next poll
      await new Promise(resolve => setTimeout(resolve, 5000));
      attempts++;

    } catch (error) {
      if (error.response?.status === 404) {
        // Generation not found yet, wait and retry
        await new Promise(resolve => setTimeout(resolve, 5000));
        attempts++;
        continue;
      }
      throw error;
    }
  }

  throw new Error("Gamma generation timed out after 2.5 minutes");
};

/**
 * Convert structured slide content to formatted text for Gamma
 * @param {object} slideContent - The JSON structure from Gemini
 * @returns {string} - Formatted text for Gamma input
 */
const formatSlidesForGamma = (slideContent) => {
  let formattedText = `# ${slideContent.title}\n\n`;

  if (slideContent.slides && Array.isArray(slideContent.slides)) {
    slideContent.slides.forEach((slide, index) => {
      if (slide.type === 'title') {
        formattedText += `## ${slide.content || slide.title}\n\n`;
      } else {
        formattedText += `## ${slide.title || `Slide ${index + 1}`}\n\n`;
        if (slide.content) {
          formattedText += `${slide.content}\n\n`;
        }
      }

      // Add image suggestion as a note
      if (slide.image_prompt) {
        formattedText += `[Hình ảnh: ${slide.image_prompt}]\n\n`;
      }

      // Speaker notes will be added as presenter notes by Gamma
      if (slide.speaker_notes) {
        formattedText += `> Ghi chú giáo viên: ${slide.speaker_notes}\n\n`;
      }

      formattedText += "---\n\n";
    });
  }

  return formattedText;
};

const generatePreschoolSlide = async (req, res) => {
  try {
    const {
      schoolName,
      teacherName,
      teacherTitle,
      ageGroup,
      topic,
      week,
      activityType,
      stockImages // boolean: true = stock, false = AI
    } = req.body;

    // Validate required fields
    if (!topic || !ageGroup) {
      return res.status(400).json({ error: "Vui lòng nhập Chủ đề và Độ tuổi" });
    }

    const fullTeacherName = teacherTitle ? `${teacherTitle} ${teacherName || "giáo"}` : (teacherName || "Cô giáo");

    // --- PROMPT ENGINEERING FOR GEMINI ---
    const systemPrompt = `
      Bạn là một Chuyên gia Giáo dục Mầm non và Thiết kế Bài giảng Điện tử (E-Learning) hàng đầu Việt Nam.
      Nhiệm vụ của bạn là soạn nội dung chi tiết cho một bộ bài giảng trình chiếu (slide) dành cho trẻ mầm non.
      
      THÔNG TIN ĐẦU VÀO:
      - Trường: ${schoolName || "Trường Mầm Non Hạnh Phúc"}
      - Giáo viên: ${fullTeacherName}
      - Lứa tuổi: ${ageGroup}
      - Chủ đề lớn: ${topic}
      - Tuần/Ngày dạy: ${week || "Tuần 1"}
      - Loại hoạt động: ${activityType || "Hoạt động học"}

      YÊU CẦU VỀ NỘI DUNG SLIDE:
      1.  **Ngôn ngữ**: Tiếng Việt 100%, trong sáng, dễ hiểu, phù hợp với trẻ mầm non. 
      2.  **Giọng điệu**: Thân thiện, hào hứng, yêu thương, khuyến khích trẻ.
      3.  **Cấu trúc bài dạy mầm non chuẩn**:
          - Slide 1: Trang bìa (Tên bài, tên trường, tên giáo viên)
          - Slide 2: Ổn định - Gây hứng thú (câu hỏi, bài hát, trò chơi nhỏ)
          - Slide 3-6: Nội dung chính (chia nhỏ kiến thức, mỗi slide 1 ý)
          - Slide 7-8: Luyện tập/Trò chơi củng cố
          - Slide cuối: Kết thúc - Nhận xét
      4.  **Số lượng**: Từ 5 đến 10 slide (không quá dài để trẻ không chán).
      5.  **Hình ảnh**: Đề xuất hình ảnh minh họa cụ thể, thân thiện với trẻ cho mỗi 2-3 slide.
      6.  **Ghi chú**: Thêm ghi chú cho giáo viên ở mỗi slide về cách giảng dạy.

      Output JSON Format (BẮT BUỘC):
      \`\`\`json
      {
        "title": "Tên bài giảng hấp dẫn bằng tiếng Việt",
        "slides": [
          {
            "id": 1,
            "type": "title",
            "title": "Tên bài học",
            "content": "Thông tin phụ (trường, lớp, giáo viên)",
            "speaker_notes": "Lời chào mừng các bé",
            "image_prompt": "Mô tả hình ảnh bìa vui nhộn, màu sắc tươi sáng"
          },
          {
            "id": 2,
            "type": "content",
            "title": "Tiêu đề slide ngắn gọn",
            "content": "Nội dung chính của slide (2-3 câu ngắn)",
            "speaker_notes": "Hướng dẫn cho giáo viên",
            "image_prompt": "Mô tả hình ảnh minh họa phù hợp"
          }
        ]
      }
      \`\`\`
    `;

    const userMessage = `Hãy soạn bài giảng cho chủ đề "${topic}" với hoạt động "${activityType || "Hoạt động học"}" cho lứa tuổi ${ageGroup}. Trường: ${schoolName || "Trường Mầm Non"}. Giáo viên: ${fullTeacherName}.`;

    console.log("Calling Cohere API...");

    // Call Cohere API
    const result = await cohere.chat({
      model: "command-a-03-2025",
      messages: [
        {
          role: "system",
          content: systemPrompt
        },
        {
          role: "user",
          content: userMessage
        }
      ]
    });

    const responseText = result.message.content[0].text;

    // Extract JSON from markdown code block if present
    let finalJsonStr = responseText;
    if (responseText.includes("```json")) {
      finalJsonStr = responseText.split("```json")[1].split("```")[0];
    } else if (responseText.includes("```")) {
      finalJsonStr = responseText.split("```")[1].split("```")[0];
    }

    let slideContent;
    try {
      slideContent = JSON.parse(finalJsonStr.trim());
    } catch (e) {
      console.error("JSON Parse Error:", e);
      console.error("Raw response:", responseText);
      return res.status(500).json({ error: "AI không thể tạo cấu trúc bài giảng hợp lệ. Vui lòng thử lại." });
    }

    console.log("Cohere generated slides:", slideContent.title);

    // --- GAMMA API INTEGRATION ---
    let gammaResult = null;

    if (GAMMA_API_KEY) {
      try {
        console.log("Calling Gamma API...");

        // Format the slide content for Gamma
        const formattedText = formatSlidesForGamma(slideContent);
        console.log("Formatted text for Gamma:", formattedText.substring(0, 200) + "...");

        // Call Gamma API to start generation
        const createResponse = await createGammaPresentation(formattedText, {
          numCards: slideContent.slides?.length || 8,
          stockImages: stockImages !== false // default to stock images
        });

        console.log("Gamma API Create Response:", createResponse);

        // Poll for the generation result to get the URL
        if (createResponse.generationId) {
          console.log("Polling for generation result...");
          const pollResult = await pollGammaGeneration(createResponse.generationId);
          console.log("Gamma Poll Result:", pollResult);

          gammaResult = {
            generationId: createResponse.generationId,
            url: pollResult.gammaUrl || pollResult.url,
            exportUrl: pollResult.exportUrl, // This is the PPTX download link
            pptxUrl: pollResult.exportUrl,   // Alias for frontend compatibility
            status: pollResult.status || "completed"
          };
        } else {
          gammaResult = createResponse;
        }

      } catch (gammaError) {
        console.error("Gamma API Error:", gammaError.message);
        gammaResult = { error: gammaError.message };
      }
    } else {
      console.log("GAMMA_API_KEY not configured, skipping Gamma integration");
      gammaResult = { error: "GAMMA_API_KEY chưa được cấu hình" };
    }

    // Return response
    res.json({
      success: true,
      gammaResult: gammaResult,
      gammaConfigured: !!GAMMA_API_KEY
    });

  } catch (error) {
    console.error("Gemini Error:", error);
    res.status(500).json({ error: "Lỗi khi tạo nội dung slide: " + error.message });
  }
};

const generateLessonPlan = async (req, res) => {
  try {
    const { topic, ageGroup, duration, objectives } = req.body;

    const systemPrompt = `Bạn là một Hiệu phó chuyên môn trường Mầm non với 20 năm kinh nghiệm.
            Nhiệm vụ: Soạn GIÁO ÁN HOẠT ĐỘNG HỌC (Text) chuẩn Bộ Giáo dục Việt Nam.
            
            CẤU TRÚC BẢNG MARKDOWN (4 cột):
            | Hoạt động | Mục đích | Chuẩn bị | Cách tiến hành |
            | :--- | :--- | :--- | :--- |
            ...
            
            Yêu cầu: Lấy trẻ làm trung tâm, STEAM, trải nghiệm thực tế.
            `;

    const userMessage = `Soạn giáo án: Đề tài ${topic}, Lứa tuổi ${ageGroup}, Thời gian ${duration}, Mục tiêu ${objectives}`;

    const result = await model.generateContent([systemPrompt, userMessage]);

    res.json({ content: result.response.text() });

  } catch (error) {
    console.error("Gemini Lesson Plan Error:", error);
    res.status(500).json({ error: error.message });
  }
};

module.exports = {
  generateLessonPlan,
  generatePreschoolSlide
};
